# Generated by Django 2.0.9 on 2019-07-30 06:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_count', models.BigIntegerField(default=0, verbose_name='阅读数')),
                ('source_type', models.SmallIntegerField(choices=[(1, '原创'), (2, '转载')], default=1, verbose_name='来源')),
                ('up_count', models.PositiveIntegerField(default=0, verbose_name='点赞的个数')),
                ('down_count', models.PositiveIntegerField(default=0, verbose_name='踩的个数')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '2.文章',
                'verbose_name_plural': '2.文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=10, verbose_name='中文类名')),
                ('foreign_name', models.CharField(max_length=20, verbose_name='英文')),
                ('widget', models.SmallIntegerField(default=500, verbose_name='权重')),
            ],
            options={
                'verbose_name': '1.类别',
                'verbose_name_plural': '1.类别',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=20, verbose_name='评论创建时间')),
                ('content', ckeditor.fields.RichTextField(verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='评论的哪篇文章')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='哪位用户的')),
            ],
            options={
                'verbose_name': '3.评论',
                'verbose_name_plural': '3.评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category', verbose_name='文章类别'),
        ),
    ]
