# Generated by Django 2.0.9 on 2019-07-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='广告路径')),
                ('img', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('name', models.CharField(max_length=20, verbose_name='广告名字')),
                ('widget', models.SmallIntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='图片')),
                ('widget', models.SmallIntegerField(default=500, verbose_name='权重')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Article')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Toolbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=10, verbose_name='工具块名')),
                ('url', models.CharField(max_length=100, verbose_name='url链接')),
            ],
            options={
                'verbose_name': '导航工具栏',
                'verbose_name_plural': '导航工具栏',
            },
        ),
    ]
